"""
run_positional_bias.py

Inference harness for the positional-bias detection follow-up study.
Extends the pilot's run_inference.py to handle permuted conditions.

Runs four conditions per model in fixed order:
  A_original -> A_perm -> B_original -> B_perm

Pre-registered condition order. All 2,000 items per condition before next.

Usage:
    python run_positional_bias.py --model llama3-8b --condition A_original
    python run_positional_bias.py --model llama3-8b --condition all
    python run_positional_bias.py --model llama3-8b --condition all_perm  # A_perm + B_perm only

Requires:
    - sampled_items.jsonl (from pilot, D:\\bcb_pilot\\data\\)
    - permutation_assignments.csv (generated by generate_permutations.py)
    - configs/config.py (from pilot)
"""

import argparse
import json
import os
import re
import sys
import time
from datetime import datetime

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from configs.config import (
    MODELS, SYSTEM_PROMPTS, DOMAINS,
    TEMPERATURE, MAX_TOKENS, N_GPU_LAYERS, CONTEXT_SIZE,
    RESULTS_DIR, DATA_DIR
)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
OPTION_LETTERS = list("ABCDEFGHIJ")
CONDITION_ORDER = ["A_original", "A_perm", "B_original", "B_perm"]

# Map our condition names to the pilot's system prompt keys
CONDITION_TO_PROMPT = {
    "A_original": "A",
    "A_perm": "A",
    "B_original": "B",
    "B_perm": "B",
}

PERM_FILE_DEFAULT = os.path.join(DATA_DIR, "permutation_assignments.csv")
RESULTS_SUBDIR = "positional_bias"


# ---------------------------------------------------------------------------
# Item loading and option parsing
# ---------------------------------------------------------------------------
def load_sampled_items():
    """Load pre-sampled items from JSONL (same as pilot)."""
    path = os.path.join(DATA_DIR, "sampled_items.jsonl")
    if not os.path.exists(path):
        print(f"ERROR: {path} not found. Run sample_items.py first.")
        sys.exit(1)
    items = []
    with open(path) as f:
        for line in f:
            items.append(json.loads(line.strip()))
    print(f"Loaded {len(items)} items from {path}")
    return items


def parse_options_from_formatted(options_formatted: str) -> list[str]:
    """
    Parse 'options_formatted' string back into a list of option texts.
    Handles formats like:
        A. option text
        B. option text
        ...
    or:
        (A) option text
        (B) option text
    Returns list of 10 option texts (without letter labels).
    """
    lines = options_formatted.strip().split("\n")
    options = []
    for line in lines:
        line = line.strip()
        if not line:
            continue
        # Try "A. text" or "A) text" or "(A) text"
        match = re.match(r'^[\(\[]?([A-J])[\)\].]?\s*[.:\-)]*\s*(.*)', line)
        if match:
            options.append(match.group(2).strip())
        else:
            # Fallback: append the whole line
            options.append(line)
    return options


def get_option_texts(item: dict) -> list[str]:
    """
    Get the list of option texts from an item.
    Tries 'options_raw' first (BCB pilot format), then 'options' (list),
    falls back to parsing 'options_formatted'.
    """
    if "options_raw" in item and isinstance(item["options_raw"], list):
        return list(item["options_raw"])
    elif "options" in item and isinstance(item["options"], list):
        return list(item["options"])
    elif "options_formatted" in item:
        return parse_options_from_formatted(item["options_formatted"])
    else:
        raise ValueError(f"Item {item.get('item_id', '?')} has no options data")


def format_options_string(option_texts: list[str]) -> str:
    """Format a list of option texts into a labelled string A. ... through J. ..."""
    lines = []
    for i, text in enumerate(option_texts):
        lines.append(f"{OPTION_LETTERS[i]}. {text}")
    return "\n".join(lines)


def apply_cyclic_shift(option_texts: list[str], k: int) -> list[str]:
    """
    Apply cyclic shift of k positions to option texts.
    Options rotate: position i gets the content from position (i - k) mod 10.
    """
    n = len(option_texts)
    return [option_texts[(i - k) % n] for i in range(n)]


def shift_answer_letter(original_letter: str, k: int) -> str:
    """Compute new correct answer letter after cyclic shift by k."""
    original_idx = OPTION_LETTERS.index(original_letter)
    new_idx = (original_idx + k) % len(OPTION_LETTERS)
    return OPTION_LETTERS[new_idx]


# ---------------------------------------------------------------------------
# Model loading (same as pilot)
# ---------------------------------------------------------------------------
def load_model(model_id):
    """Load a GGUF model via llama-cpp-python with Vulkan backend."""
    try:
        from llama_cpp import Llama
    except ImportError:
        print("ERROR: llama-cpp-python not installed.")
        sys.exit(1)

    model_cfg = MODELS[model_id]
    gguf_path = model_cfg["gguf_path"]

    if gguf_path is None or not os.path.exists(gguf_path):
        try:
            from configs.local_config import MODEL_PATHS
            gguf_path = MODEL_PATHS.get(model_id)
        except ImportError:
            pass

    if gguf_path is None or not os.path.exists(gguf_path):
        print(f"ERROR: GGUF path not set for {model_id}.")
        print(f"  Create configs/local_config.py with MODEL_PATHS dict.")
        sys.exit(1)

    print(f"Loading {model_cfg['name']} from {gguf_path}...")
    t0 = time.time()
    llm = Llama(
        model_path=gguf_path,
        n_gpu_layers=N_GPU_LAYERS,
        n_ctx=CONTEXT_SIZE,
        verbose=False,
    )
    print(f"  Loaded in {time.time() - t0:.1f}s")
    return llm


# ---------------------------------------------------------------------------
# Response parsing (same as pilot)
# ---------------------------------------------------------------------------
def parse_response(raw_output):
    """Parse model output to extract a single letter A-J."""
    if not raw_output or raw_output.startswith("ERROR:"):
        return None, False

    text = raw_output.strip()

    if len(text) == 1 and text.upper() in "ABCDEFGHIJ":
        return text.upper(), True

    if len(text) >= 1 and text[0].upper() in "ABCDEFGHIJ":
        if len(text) == 1 or text[1] in ".,:;) \t\n":
            return text[0].upper(), True

    match = re.search(r'\b([A-J])\b', text.upper())
    if match:
        found = match.group(1)
        start = match.start()
        end = match.end()
        before_ok = (start == 0 or not text[start - 1].isalpha())
        after_ok = (end == len(text) or not text[end].isalpha()
                    if end < len(text) else True)
        if before_ok and after_ok:
            return found, True

    return None, False


# ---------------------------------------------------------------------------
# Trial execution
# ---------------------------------------------------------------------------
def run_single_trial(llm, system_prompt, user_message, temperature=0.0):
    """Run a single trial and return the raw output."""
    try:
        response = llm.create_chat_completion(
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ],
            temperature=temperature,
            max_tokens=MAX_TOKENS,
        )
        raw_output = response["choices"][0]["message"]["content"]
        return raw_output.strip()
    except Exception as e:
        return f"ERROR: {str(e)}"


# ---------------------------------------------------------------------------
# Condition runner
# ---------------------------------------------------------------------------
def run_condition(llm, model_id, condition, items, perm_df, temperature=0.0):
    """
    Run all items for one model x one condition.
    
    For permuted conditions (A_perm, B_perm), applies cyclic shift from perm_df.
    For original conditions (A_original, B_original), uses original option order.
    """
    out_dir = os.path.join(RESULTS_DIR, RESULTS_SUBDIR)
    os.makedirs(out_dir, exist_ok=True)
    output_path = os.path.join(out_dir, f"{model_id}_{condition}.jsonl")

    is_permuted = condition.endswith("_perm")
    prompt_key = CONDITION_TO_PROMPT[condition]

    # Resume support
    completed_ids = set()
    if os.path.exists(output_path):
        with open(output_path) as f:
            for line in f:
                rec = json.loads(line.strip())
                completed_ids.add(rec["item_id"])
        print(f"  Resuming: {len(completed_ids)} trials already completed.")

    remaining = [it for it in items if it["item_id"] not in completed_ids]
    total = len(items)
    done = len(completed_ids)

    print(f"  Running {model_id} / {condition} "
          f"({done}/{total} done, {len(remaining)} remaining)")

    # Build item_id -> shift_k lookup
    shift_lookup = {}
    if is_permuted:
        for _, row in perm_df.iterrows():
            shift_lookup[row["item_id"]] = int(row["shift_k"])

    with open(output_path, "a") as f:
        for i, item in enumerate(remaining):
            item_id = item["item_id"]
            domain = item["domain"]

            # Get option texts
            option_texts = get_option_texts(item)
            original_answer = item["answer"]
            shift_k = 0

            if is_permuted:
                shift_k = shift_lookup.get(item_id, 0)
                if shift_k == 0:
                    print(f"  WARNING: No shift found for item {item_id}, using k=0")
                option_texts = apply_cyclic_shift(option_texts, shift_k)
                correct_answer = shift_answer_letter(original_answer, shift_k)
            else:
                correct_answer = original_answer

            # Format prompt
            system_prompt = SYSTEM_PROMPTS[prompt_key].format(domain=domain)
            options_str = format_options_string(option_texts)
            user_message = f"{item['question']}\n\n{options_str}"

            # Run trial
            t0 = time.time()
            raw_output = run_single_trial(llm, system_prompt, user_message,
                                          temperature=temperature)
            elapsed = time.time() - t0

            # Parse
            parsed_letter, is_valid = parse_response(raw_output)

            # Score
            correct = None
            if is_valid and parsed_letter is not None:
                correct = int(parsed_letter == correct_answer)

            # Record
            record = {
                "model_id": model_id,
                "domain": domain,
                "condition": condition,
                "item_id": item_id,
                "shift_k": shift_k,
                "original_answer": original_answer,
                "answer_key": correct_answer,
                "options_order": "permuted" if is_permuted else "original",
                "raw_output": raw_output,
                "parsed_response": parsed_letter,
                "is_valid": is_valid,
                "correct": correct,
                "temperature": temperature,
                "elapsed_s": round(elapsed, 3),
                "timestamp": datetime.utcnow().isoformat(),
            }

            f.write(json.dumps(record) + "\n")
            f.flush()

            done += 1
            if done % 50 == 0 or done == total:
                status = "correct" if correct else "wrong/missing"
                print(f"    [{done}/{total}] "
                      f"resp={parsed_letter} ({status}) "
                      f"shift_k={shift_k} "
                      f"({elapsed:.2f}s)")

    print(f"  {condition} complete. Output: {output_path}")
    return output_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def get_conditions_to_run(condition_arg):
    """Expand condition argument into ordered list."""
    if condition_arg == "all":
        return CONDITION_ORDER
    elif condition_arg == "all_perm":
        return ["A_perm", "B_perm"]
    elif condition_arg == "all_original":
        return ["A_original", "B_original"]
    elif condition_arg in CONDITION_ORDER:
        return [condition_arg]
    else:
        print(f"ERROR: Unknown condition '{condition_arg}'")
        print(f"  Valid: {', '.join(CONDITION_ORDER)}, all, all_perm, all_original")
        sys.exit(1)


def main():
    parser = argparse.ArgumentParser(
        description="Positional-bias detection study — Inference"
    )
    parser.add_argument(
        "--model", required=True, choices=list(MODELS.keys()),
        help="Model ID"
    )
    parser.add_argument(
        "--condition", required=True,
        help="Condition: A_original, A_perm, B_original, B_perm, all, all_perm, all_original"
    )
    parser.add_argument(
        "--permutations", type=str, default=PERM_FILE_DEFAULT,
        help=f"Path to permutation assignments CSV (default: {PERM_FILE_DEFAULT})"
    )
    parser.add_argument(
        "--temperature", type=float, default=0.0,
        help="Temperature (default: 0.0 = greedy)"
    )
    args = parser.parse_args()

    # Load items
    items = load_sampled_items()

    # Load permutations
    perm_path = args.permutations
    if not os.path.exists(perm_path):
        print(f"ERROR: Permutation file not found: {perm_path}")
        print(f"  Run generate_permutations.py first.")
        sys.exit(1)
    perm_df = pd.read_csv(perm_path)
    print(f"Loaded {len(perm_df)} permutation assignments from {perm_path}")

    # Load model
    llm = load_model(args.model)

    # Run conditions
    conditions = get_conditions_to_run(args.condition)
    print(f"\nCondition order: {' -> '.join(conditions)}")
    print(f"Temperature: {args.temperature}")
    print()

    for cond in conditions:
        run_condition(llm, args.model, cond, items, perm_df, args.temperature)

    print("\nAll done.")


if __name__ == "__main__":
    main()
